# -*- coding: utf-8 -*-
"""Stellaris 目录覆盖规则表。

数据取自 Stellaris 官方 wiki 的 Modding 页面 Common folder 覆盖规则总表：
https://stellaris.paradoxwikis.com/Modding  （章节 Common folder）

wiki 对每个目录给出 Overwrite Type，取值含义：
    LIOS        Last In Only Served，文件名靠后者胜
    FIOS        First In Only Served，文件名靠前者胜
    DUPL        多份定义并存（往往需整份替换原文件才生效）
    NO          不能单独覆盖
    DUPL_LIOS   DUPL 与 LIOS 混合
    DUPL_NO     DUPL 与 NO 混合
    NO_DUPL_FIOS  NO / DUPL / FIOS 混合
    MERGE       同名条目合并，不互相覆盖
    UNKNOWN     wiki 自身标注为 ?，语义未验证

wiki 原始表把子目录写成 ├─── 树形，这里已拼成 parent/child 全路径。
本文件由生成脚本从 wiki wikitext 解析产出，不要手改；要更新就重跑生成。
"""

# 目录 -> 覆盖类型
WIKI_COMMON_OVERWRITE = {
    "achievements": "UNKNOWN",
    "agreement_presets": "UNKNOWN",
    "agreement_resources": "UNKNOWN",
    "agreement_term_values": "LIOS",
    "agreement_terms": "UNKNOWN",
    "ai_budget": "UNKNOWN",
    "ai_espionage": "UNKNOWN",
    "ai_espionage/operations": "UNKNOWN",
    "ai_espionage/spynetworks": "UNKNOWN",
    "ambient_objects": "UNKNOWN",
    "anomalies": "LIOS",
    "archaeological_site_types": "UNKNOWN",
    "armies": "LIOS",
    "artifact_actions": "LIOS",
    "ascension_perk_categories": "LIOS",
    "ascension_perks": "LIOS",
    "asteroid_belts": "UNKNOWN",
    "astral_actions": "LIOS",
    "attitudes": "LIOS",
    "bombardment_stances": "LIOS",
    "buildings": "LIOS",
    "button_effects": "LIOS",
    "bypass": "LIOS",
    "casus_belli": "LIOS",
    "colony_automation": "UNKNOWN",
    "colony_automation_categories": "LIOS",
    "colony_automation_exceptions": "UNKNOWN",
    "colony_types": "LIOS",
    "colors": "UNKNOWN",
    "component_sets": "FIOS",
    "component_slot_templates": "UNKNOWN",
    "component_tags": "UNKNOWN",
    "component_templates": "FIOS",
    "council_agendas": "LIOS",
    "country_container": "UNKNOWN",
    "country_customization": "UNKNOWN",
    "country_focus": "LIOS",
    "country_limits": "LIOS",
    "country_limits/ownership_limits": "LIOS",
    "country_limits/ship_of_size_limits": "LIOS",
    "country_types": "LIOS",
    "crisis_levels": "LIOS",
    "crisis_objectives": "LIOS",
    "decisions": "LIOS",
    "defines": "LIOS",
    "deposit_categories": "UNKNOWN",
    "deposits": "LIOS",
    "diplo_phrases": "UNKNOWN",
    "diplomatic_actions": "LIOS",
    "diplomatic_economy": "LIOS",
    "districts": "LIOS",
    "dynamic_text": "UNKNOWN",
    "economic_categories": "LIOS",
    "economic_plans": "UNKNOWN",
    "edicts": "LIOS",
    "espionage_assets": "LIOS",
    "espionage_operation_categories": "UNKNOWN",
    "espionage_operation_types": "LIOS",
    "ethics": "LIOS",
    "event_chains": "FIOS",
    "fallen_empires": "UNKNOWN",
    "federation_law_categories": "UNKNOWN",
    "federation_laws": "UNKNOWN",
    "federation_perks": "UNKNOWN",
    "federation_types": "UNKNOWN",
    "first_contact": "UNKNOWN",
    "galactic_community_actions": "UNKNOWN",
    "galactic_focuses": "UNKNOWN",
    "game_concept_categories": "UNKNOWN",
    "game_rules": "LIOS",
    "gamesetup_settings": "UNKNOWN",
    "global_ship_designs": "FIOS",
    "governments": "LIOS",
    "governments/authorities": "FIOS",
    "governments/civics": "LIOS",
    "graphical_culture": "UNKNOWN",
    "greeting_overlay_sounds": "UNKNOWN",
    "inline_scripts": "DUPL",
    "intel_categories": "UNKNOWN",
    "intel_levels": "UNKNOWN",
    "job_tags": "UNKNOWN",
    "lawsuits": "UNKNOWN",
    "leader_classes": "LIOS",
    "leader_tiers": "UNKNOWN",
    "mandates": "LIOS",
    "map_modes": "LIOS",
    "megastructures": "LIOS",
    "menace_perks": "UNKNOWN",
    "message_types": "UNKNOWN",
    "missions": "UNKNOWN",
    "mutations": "UNKNOWN",
    "name_lists": "DUPL",
    "notification_modifiers": "UNKNOWN",
    "observation_station_missions": "DUPL_LIOS",
    "on_actions": "MERGE",
    "opinion_modifiers": "DUPL_LIOS",
    "patrons": "LIOS",
    "patrons/deeds": "LIOS",
    "personalities": "LIOS",
    "planet_classes": "DUPL_LIOS",
    "planet_modifiers": "LIOS",
    "policies": "LIOS",
    "pop_categories": "LIOS",
    "pop_faction_types": "LIOS",
    "pop_jobs": "LIOS",
    "precursor_civilizations": "UNKNOWN",
    "prescripted_flags": "UNKNOWN",
    "random_names": "UNKNOWN",
    "random_names/base": "UNKNOWN",
    "relics": "LIOS",
    "resolution_categories": "UNKNOWN",
    "resolution_groups": "LIOS",
    "resolutions": "LIOS",
    "script_values": "LIOS",
    "scripted_effects": "LIOS",
    "scripted_loc": "FIOS",
    "scripted_modifiers": "LIOS",
    "scripted_triggers": "LIOS",
    "scripted_variables": "FIOS",
    "section_templates": "NO_DUPL_FIOS",
    "sector_focuses": "LIOS",
    "sector_types": "UNKNOWN",
    "ship_behaviors": "FIOS",
    "ship_categories": "UNKNOWN",
    "ship_sets": "UNKNOWN",
    "ship_sizes": "LIOS",
    "situations": "LIOS",
    "solar_system_initializers": "FIOS",
    "special_projects": "FIOS",
    "specialist_subject_perks": "LIOS",
    "specialist_subject_types": "LIOS",
    "species_archetypes": "LIOS",
    "species_classes": "LIOS",
    "species_names": "UNKNOWN",
    "species_rights": "LIOS",
    "specimens": "LIOS",
    "star_classes": "LIOS",
    "starbase_buildings": "LIOS",
    "starbase_levels": "LIOS",
    "starbase_modules": "LIOS",
    "starbase_types": "LIOS",
    "start_screen_messages": "FIOS",
    "static_modifiers": "LIOS",
    "storm_types": "UNKNOWN",
    "strategic_resources": "DUPL",
    "system_tooltips": "UNKNOWN",
    "system_types": "LIOS",
    "target_types": "UNKNOWN",
    "technology": "LIOS",
    "technology/category": "UNKNOWN",
    "technology/tier": "LIOS",
    "terraform": "DUPL",
    "timeline_events": "UNKNOWN",
    "tradition_categories": "LIOS",
    "traditions": "LIOS",
    "trait_tags": "UNKNOWN",
    "traits": "DUPL_NO",
    "war_goals": "LIOS",
    "zone_slots": "UNKNOWN",
    "zones": "UNKNOWN",
}

# 目录 -> wiki 原始标注（保留 since vX.Y 等版本附注）
WIKI_RAW_TYPE = {
    "achievements": '❓',
    "agreement_presets": '❓',
    "agreement_resources": '❓',
    "agreement_term_values": 'LIOS',
    "agreement_terms": '❓',
    "ai_budget": '❓',
    "ai_espionage": '❓',
    "ai_espionage/operations": '❓',
    "ai_espionage/spynetworks": '❓',
    "ambient_objects": '❓',
    "anomalies": 'LIOS',
    "archaeological_site_types": '❓',
    "armies": 'LIOS',
    "artifact_actions": 'LIOS',
    "ascension_perk_categories": 'LIOS',
    "ascension_perks": 'LIOS',
    "asteroid_belts": '❓',
    "astral_actions": 'LIOS',
    "attitudes": 'LIOS',
    "bombardment_stances": 'LIOS',
    "buildings": 'LIOS|since v3.3',
    "button_effects": 'LIOS',
    "bypass": 'LIOS',
    "casus_belli": 'LIOS',
    "colony_automation": '❓',
    "colony_automation_categories": 'LIOS',
    "colony_automation_exceptions": '❓',
    "colony_types": 'LIOS',
    "colors": '❓',
    "component_sets": 'FIOS',
    "component_slot_templates": '❓',
    "component_tags": '❓',
    "component_templates": 'FIOS',
    "council_agendas": 'LIOS',
    "country_container": '❓',
    "country_customization": '❓',
    "country_focus": 'LIOS',
    "country_limits": 'LIOS',
    "country_limits/ownership_limits": 'LIOS',
    "country_limits/ship_of_size_limits": 'LIOS',
    "country_types": 'LIOS',
    "crisis_levels": 'LIOS',
    "crisis_objectives": 'LIOS',
    "decisions": 'LIOS',
    "defines": 'LIOS',
    "deposit_categories": '❓',
    "deposits": 'LIOS',
    "diplo_phrases": '❓',
    "diplomatic_actions": 'LIOS',
    "diplomatic_economy": 'LIOS',
    "districts": 'LIOS|since v3.3',
    "dynamic_text": '❓',
    "economic_categories": 'LIOS',
    "economic_plans": '❓',
    "edicts": 'LIOS',
    "espionage_assets": 'LIOS',
    "espionage_operation_categories": '❓',
    "espionage_operation_types": 'LIOS',
    "ethics": 'LIOS',
    "event_chains": 'FIOS',
    "fallen_empires": '❓',
    "federation_law_categories": '❓',
    "federation_laws": '❓',
    "federation_perks": '❓',
    "federation_types": '❓',
    "first_contact": '❓',
    "galactic_community_actions": '❓',
    "galactic_focuses": '❓',
    "game_concept_categories": '❓',
    "game_rules": 'LIOS',
    "gamesetup_settings": '❓',
    "global_ship_designs": 'FIOS',
    "governments": 'LIOS',
    "governments/authorities": 'FIOS',
    "governments/civics": 'LIOS',
    "graphical_culture": '❓',
    "greeting_overlay_sounds": '❓',
    "inline_scripts": 'DUPL',
    "intel_categories": '❓',
    "intel_levels": '❓',
    "job_tags": '❓',
    "lawsuits": '❓',
    "leader_classes": 'LIOS',
    "leader_tiers": '❓',
    "mandates": 'LIOS',
    "map_modes": 'LIOS',
    "megastructures": 'LIOS',
    "menace_perks": '❓',
    "message_types": '❓',
    "missions": '❓',
    "mutations": '❓',
    "name_lists": 'DUPL',
    "notification_modifiers": '❓',
    "observation_station_missions": 'DUPL/LIOS',
    "on_actions": 'NO/MERGE',
    "opinion_modifiers": 'DUPL/LIOS',
    "patrons": 'LIOS',
    "patrons/deeds": 'LIOS',
    "personalities": 'LIOS',
    "planet_classes": 'DUPL/LIOS',
    "planet_modifiers": 'LIOS',
    "policies": 'LIOS',
    "pop_categories": 'LIOS',
    "pop_faction_types": 'LIOS',
    "pop_jobs": 'LIOS|since v3.3',
    "precursor_civilizations": '❓',
    "prescripted_flags": '❓',
    "random_names": '❓',
    "random_names/base": '❓',
    "relics": 'LIOS',
    "resolution_categories": '❓',
    "resolution_groups": 'LIOS',
    "resolutions": 'LIOS',
    "script_values": 'LIOS',
    "scripted_effects": 'LIOS',
    "scripted_loc": 'FIOS',
    "scripted_modifiers": 'LIOS',
    "scripted_triggers": 'LIOS',
    "scripted_variables": 'FIOS',
    "section_templates": 'NO DUPL/FIOS',
    "sector_focuses": 'LIOS',
    "sector_types": '❓',
    "ship_behaviors": 'FIOS',
    "ship_categories": '❓',
    "ship_sets": '❓',
    "ship_sizes": 'LIOS',
    "situations": 'LIOS',
    "solar_system_initializers": 'FIOS',
    "special_projects": 'FIOS',
    "specialist_subject_perks": 'LIOS',
    "specialist_subject_types": 'LIOS',
    "species_archetypes": 'LIOS',
    "species_classes": 'LIOS',
    "species_names": '❓',
    "species_rights": 'LIOS',
    "specimens": 'LIOS',
    "star_classes": 'LIOS',
    "starbase_buildings": 'LIOS',
    "starbase_levels": 'LIOS',
    "starbase_modules": 'LIOS',
    "starbase_types": 'LIOS',
    "start_screen_messages": 'FIOS',
    "static_modifiers": 'LIOS',
    "storm_types": '❓',
    "strategic_resources": 'DUPL',
    "system_tooltips": '❓',
    "system_types": 'LIOS',
    "target_types": '❓',
    "technology": 'LIOS*',
    "technology/category": '❓',
    "technology/tier": 'LIOS',
    "terraform": 'DUPL',
    "timeline_events": '❓',
    "tradition_categories": 'LIOS',
    "traditions": 'LIOS',
    "trait_tags": '❓',
    "traits": 'DUPL/NO',
    "war_goals": 'LIOS',
    "zone_slots": '❓',
    "zones": '❓',
}

# 目录 -> (错误日志形态, wiki 注意事项)，仅收录非空项
WIKI_NOTES = {
    "achievements": ('❓', ''),
    "agreement_presets": ('❓', 'Functions are limited/restricted by:|diplomatic_actions and game_rules'),
    "agreement_resources": ('❓', ''),
    "agreement_term_values": ('Object with key already exists', 'LIOS override works despite the error entry; verified in v4.3.7 with two files defining the same subject_dna term values.'),
    "agreement_terms": ('❓', ''),
    "ai_budget": ('❓', ''),
    "ai_espionage": ('❓', ''),
    "ai_espionage/operations": ('❓', ''),
    "ai_espionage/spynetworks": ('❓', ''),
    "ambient_objects": ('❓', 'References used by code to spawn ambient objects.'),
    "anomalies": ('Object key already exists', 'Events that occur for research ships'),
    "archaeological_site_types": ('❓', 'Definitions for Archaeological Sites to be discovered and delved by Science Ships.'),
    "armies": ('Object key already exists', ''),
    "artifact_actions": ('Object key already exists', ''),
    "ascension_perk_categories": ('Object key already exists', ''),
    "ascension_perks": ('[None]|since v3.0', 'Pre v3.0: [Error log] Object key already exists'),
    "asteroid_belts": ('❓', ''),
    "astral_actions": ('Object key already exists', ''),
    "attitudes": ('Object key already exists', ''),
    "bombardment_stances": ('Object key already exists', ''),
    "buildings": ('Object key already exists', 'Pre v3.3: Breaks auto-generated modifiers'),
    "button_effects": ('Object key already exists', ''),
    "bypass": ('Object key already exists', ''),
    "casus_belli": ('Object key already exists', ''),
    "colony_automation": ('❓', ''),
    "colony_automation_categories": ('Object key already exists', ''),
    "colony_automation_exceptions": ('❓', ''),
    "colony_types": ('Object key already exists', ''),
    "colors": ('❓', ''),
    "component_sets": ('Object key already exists', ''),
    "component_slot_templates": ('❓', ''),
    "component_tags": ('❓', ''),
    "component_templates": ('Object key already exists', ''),
    "council_agendas": ('Object key already exists', 'Agendas are given to leader-candidates in Oligarchic government-forms'),
    "country_container": ('❓', ''),
    "country_customization": ('❓', ''),
    "country_focus": ('Object key already exists', ''),
    "country_limits": ('❓', ''),
    "country_limits/ownership_limits": ('Object key already exists', ''),
    "country_limits/ship_of_size_limits": ('Object key already exists', ''),
    "country_types": ('[None]|since v3.0', 'Pre v3.0: [Error log] Object key already exists'),
    "crisis_levels": ('❓', ''),
    "crisis_objectives": ('❓', ''),
    "decisions": ('Object key already exists', ''),
    "defines": ('', 'The block the define is in must be included as well.'),
    "deposit_categories": ('❓', ''),
    "deposits": ('Object key already exists', ''),
    "diplo_phrases": ('❓', ''),
    "diplomatic_actions": ('Object key already exists', ''),
    "diplomatic_economy": ('Object key already exists', ''),
    "districts": ('Object key already exists', 'Pre v3.3: Breaks auto-generated modifiers'),
    "dynamic_text": ('❓', ''),
    "economic_categories": ('Object key already exists', ''),
    "economic_plans": ('❓', ''),
    "edicts": ('Object key already exists', ''),
    "espionage_assets": ('❓', 'Entire override : PASS'),
    "espionage_operation_categories": ('❓', ''),
    "espionage_operation_types": ('… already exists, using the one at file: …', 'Entire override : PASS'),
    "ethics": ('Object key already exists', 'Might break "selected ethic" graphic if too many Ethics; WARNING: Due to new multiple ethics files, the auto-generated file will randomly break off as some empires have no ethics when randomly generated. So entire overwrite is suggested.'),
    "fallen_empires": ('❓', ''),
    "federation_law_categories": ('❓', ''),
    "federation_laws": ('❓', ''),
    "federation_perks": ('❓', ''),
    "federation_types": ('❓', ''),
    "first_contact": ('❓', ''),
    "galactic_community_actions": ('❓', ''),
    "galactic_focuses": ('❓', ''),
    "game_concept_categories": ('❓', ''),
    "gamesetup_settings": ('❓', ''),
    "global_ship_designs": ('A ship design already exists', ''),
    "governments": ('Object key already exists', ''),
    "governments/authorities": ('Object key already exists', 'Specific override is impossible. Entries override ONLY.'),
    "governments/civics": ('Object key already exists', ''),
    "graphical_culture": ('❓', ''),
    "greeting_overlay_sounds": ('❓', ''),
    "inline_scripts": ('❓', 'Only works when the file is fully replaced in my experience'),
    "intel_categories": ('❓', ''),
    "intel_levels": ('❓', ''),
    "job_tags": ('❓', ''),
    "lawsuits": ('❓', ''),
    "leader_classes": ('Object key already exists', ''),
    "leader_tiers": ('❓', ''),
    "mandates": ('Object key already exists', ''),
    "map_modes": ('Object key already exists', ''),
    "megastructures": ('Object key already exists', ''),
    "menace_perks": ('❓', ''),
    "message_types": ('❓', ''),
    "missions": ('❓', ''),
    "mutations": ('❓', ''),
    "name_lists": ('❓', ''),
    "notification_modifiers": ('❓', ''),
    "observation_station_missions": ('❓', 'Entire override ONLY.'),
    "on_actions": ('', 'Cannot modify existing entries; new entries will be merged with the existing entry with the same NAME={}.'),
    "opinion_modifiers": ('', 'add_opinion_modifier is LIOS'),
    "patrons": ('Object key already exists', ''),
    "patrons/deeds": ('Object key already exists', ''),
    "personalities": ('Object key already exists', ''),
    "planet_classes": ('', 'DUPL – breaks habitability modifiers if individually overwritten.'),
    "planet_modifiers": ('Object key already exists', ''),
    "policies": ('Object key already exists', 'Existing Object key can be override with NAME = {}'),
    "pop_categories": ('Object key already exists', ''),
    "pop_faction_types": ('Object key already exists', ''),
    "pop_jobs": ('Object key already exists', 'Pre v3.3: [Type] NO – Breaks auto-generated modifiers if overwriting a specific job and not the whole file.'),
    "precursor_civilizations": ('❓', ''),
    "prescripted_flags": ('❓', ''),
    "random_names": ('❓', ''),
    "random_names/base": ('❓', ''),
    "relics": ('Object with key already exists', ''),
    "resolution_categories": ('❓', ''),
    "resolution_groups": ('Object with key already exists', ''),
    "resolutions": ('Object with key already exists', ''),
    "script_values": ('Object with key already exists', ''),
    "scripted_effects": ('Object key already exists', ''),
    "scripted_loc": ('', 'Existing Object key can be override with name = key'),
    "scripted_modifiers": ('Object key already exists', ''),
    "scripted_triggers": ('Object key already exists', ''),
    "scripted_variables": ('Variable name taken', ''),
    "section_templates": ('Duplicate section template found. Multiple sections are named …', "Warning: existing can't be overwritten, used ships/starbases will get deleted."),
    "sector_focuses": ('Object key already exists', ''),
    "sector_types": ('❓', ''),
    "ship_behaviors": ('Behavior name already exists', ''),
    "ship_categories": ('❓', ''),
    "ship_sets": ('❓', ''),
    "ship_sizes": ('Object key already exists', ''),
    "situations": ('Object key already exists', ''),
    "solar_system_initializers": ('Initializer already exists', ''),
    "special_projects": ('Object key already exists', ''),
    "specialist_subject_perks": ('❓', ''),
    "specialist_subject_types": ('❓', ''),
    "species_archetypes": ('Object key already exists', 'Pre v3.3: Breaks auto-generated modifiers.'),
    "species_classes": ('Object key already exists', ''),
    "species_names": ('❓', ''),
    "species_rights": ('Object key already exists', 'Effect tooltips are independent of the effects.'),
    "specimens": ('❓', ''),
    "star_classes": ('❓', ''),
    "starbase_buildings": ('Object key already exists', ''),
    "starbase_levels": ('Object key already exists', ''),
    "starbase_modules": ('Object key already exists', ''),
    "starbase_types": ('Object key already exists', ''),
    "start_screen_messages": ('', 'The first valid part for each location will be used and the rest discarded without issue.'),
    "storm_types": ('❓', ''),
    "strategic_resources": ('', "Must replace the whole file with the same filename or it won't work."),
    "system_tooltips": ('❓', ''),
    "system_types": ('Object key already exists', ''),
    "target_types": ('❓', ''),
    "technology": ('Duplicate technology: [tech]', 'LIOS overrides mostly still work despite the DUPL-type error entry. However, if the overwriting tech lacks a "potential" block, it will inherit the "potential" block from the overwritten tech.'),
    "technology/category": ('❓', ''),
    "technology/tier": ('❓', ''),
    "timeline_events": ('❓', ''),
    "tradition_categories": ('Object key already exists', ''),
    "traditions": ('Object key already exists', 'Effect tooltips are independent of the effects.'),
    "trait_tags": ('❓', ''),
    "traits": ('', 'Entire override ONLY.'),
    "war_goals": ('Object key already exists', ''),
    "zone_slots": ('❓', ''),
    "zones": ('❓', ''),
}

# 本地实测与 wiki 结论不一致的目录 -> (wiki 类型, 本地实测说明)
# 判定仍按 wiki，但详情里会并列提示本地实测结论，避免静默取舍。
CONTESTED = {
    "component_templates": ('FIOS', "本地 2026-09-15 实测：用 '!' 前缀抢 First In 仍报 Component template key used multiple times，游戏仍用原版那份，改名无效；唯一可行做法是同路径整份替换原版文件。wiki 标 FIOS（靠前者胜）。两者结论不同，本工具按 wiki 判定，此处提示存疑。"),
    "opinion_modifiers": ('DUPL_LIOS', 'add_opinion_modifier 为 LIOS，其余条目可能重复并存。'),
    "planet_classes": ('DUPL_LIOS', '单独覆盖会破坏宜居度修正，建议整份替换。'),
    "section_templates": ('NO_DUPL_FIOS', '本地实测：已存在的 section template 不能被覆盖，覆盖会连带删除使用它的舰船/基地。'),
    "strategic_resources": ('DUPL', '本地实测：必须同路径整份替换原版文件，否则不生效。'),
    "terraform": ('DUPL', '本地实测：必须同路径整份替换原版文件，否则不生效。'),
    "traits": ('DUPL_NO', '本地实测：必须同路径整份替换原版文件，否则不生效。'),
}
